Once upon a time, in a forest, there lived a monkey who resided on a jamoon (berry )tree,which was on the banks of a river. In the samw forest there lived a crocodile and his wife….

on day, the crocodile came to the banks of the river and rested under the tree. the kindhearted monkey offered him some fruits. the crocodile came back the next day for more fruits, as he loved them. as days passed by, the crocodile and the monkey became good friends...
